export enum MigrationEvent {

    MIGRATION_STARTED = 'MIGRATION_STARTED',

    STAGE_STARTED = 'STAGE_STARTED',

    STAGE_COMPLETED = 'STAGE_COMPLETED',

    MIGRATION_COMPLETED = 'MIGRATION_COMPLETED',

    MIGRATION_FAILED = 'MIGRATION_FAILED'

}